### ISSUE TITLE
Design Update: Initial Design

### ISSUE THREAD

**Issue by Eugenepark215** [Eugenepark215/HowMuchDoINeedToAffordHome#1]
## 🖼️ Wireframes

> ##### Updated wireframe(s) of what the app should look like when the updates are ready.

![Screenshot 2023-03-28 at 6 16 38 PM](https://user-images.githubusercontent.com/97265272/228409118-3e505208-3d03-4d13-9470-421d331c71a3.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that don't do anything.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
